package ecommerce.analytics

import ecommerce.model.{Product, Transaction}
import org.apache.spark.rdd.RDD

/** Analytics that require both [[Transaction]] and [[Product]] data.
  *
  * This object is where transactions and products are related to each
  * other via `productId`, using Spark's RDD `join` (and `leftOuterJoin`).
  * It contains no I/O: it only consumes already-parsed, valid RDDs and
  * produces new RDDs (or, for the top-N case, a small local `Array`).
  */
object ProductAnalytics {

  /** Computes the revenue generated by each transaction: `price * quantity`. */
  private def revenue(transaction: Transaction): Double =
    transaction.price * transaction.quantity

  /** Joins transactions with their referenced product and computes total
    * revenue per product name.
    *
    * Demonstrates the required Spark `join`: transactions are keyed by
    * `productId` (`map`), products are keyed by `productId` (`map`), and
    * the two RDDs are related with `join`, producing
    * `RDD[(Long, (Transaction, Product))]`. The joined pairs are then
    * projected to `(productName, revenue)` (`map`) and summed with
    * `reduceByKey`.
    *
    * @param transactions the RDD of parsed, valid transactions
    * @param products     the RDD of parsed, valid products
    * @return an RDD of `(productName, totalRevenue)` pairs
    */
  def revenueByProduct(transactions: RDD[Transaction], products: RDD[Product]): RDD[(String, Double)] = {
    val transactionsByProduct = transactions.map(transaction => transaction.productId -> transaction)
    val productsById = products.map(product => product.productId -> product)

    transactionsByProduct
      .join(productsById)
      .map { case (_, (transaction, product)) => product.name -> revenue(transaction) }
      .reduceByKey(_ + _)
  }

  /** Returns the top products ranked by total revenue, highest first.
    *
    * Built on top of [[revenueByProduct]]. The final ranking uses Spark's
    * `takeOrdered`, which selects the top elements in a distributed manner
    * without collecting the whole dataset locally before sorting.
    *
    * @param transactions the RDD of parsed, valid transactions
    * @param products     the RDD of parsed, valid products
    * @param limit        maximum number of products to return; non-positive
    *                     values yield an empty result
    * @return the top `limit` `(productName, totalRevenue)` pairs, highest revenue first
    */
  def topProductsByRevenue(transactions: RDD[Transaction], products: RDD[Product], limit: Int): Array[(String, Double)] =
    if (limit <= 0) Array.empty
    else revenueByProduct(transactions, products).takeOrdered(limit)(Ordering.by[(String, Double), Double](_._2).reverse)

  /** Joins transactions with their referenced product and computes the
    * total quantity sold per product name.
    *
    * @param transactions the RDD of parsed, valid transactions
    * @param products     the RDD of parsed, valid products
    * @return an RDD of `(productName, totalQuantitySold)` pairs
    */
  def quantitySoldByProduct(transactions: RDD[Transaction], products: RDD[Product]): RDD[(String, Int)] = {
    val transactionsByProduct = transactions.map(transaction => transaction.productId -> transaction)
    val productsById = products.map(product => product.productId -> product)

    transactionsByProduct
      .join(productsById)
      .map { case (_, (transaction, product)) => product.name -> transaction.quantity }
      .reduceByKey(_ + _)
  }

  /** Computes total revenue per product category, using the category from
    * the joined [[Product]] record (rather than the transaction's own
    * `category` field), so the result reflects the current product catalog.
    *
    * @param transactions the RDD of parsed, valid transactions
    * @param products     the RDD of parsed, valid products
    * @return an RDD of `(category, totalRevenue)` pairs
    */
  def revenueByProductCategory(transactions: RDD[Transaction], products: RDD[Product]): RDD[(String, Double)] = {
    val transactionsByProduct = transactions.map(transaction => transaction.productId -> transaction)
    val productsById = products.map(product => product.productId -> product)

    transactionsByProduct
      .join(productsById)
      .map { case (_, (transaction, product)) => product.category -> revenue(transaction) }
      .reduceByKey(_ + _)
  }

  /** Identifies transactions that reference a `productId` with no matching
    * entry in the product catalog.
    *
    * Uses a Spark `leftOuterJoin`: each transaction is kept regardless of
    * whether a matching product exists, and pattern matching on the
    * resulting `Option[Product]` (`None` case) filters down to the
    * transactions with a missing reference.
    *
    * @param transactions the RDD of parsed, valid transactions
    * @param products     the RDD of parsed, valid products
    * @return an RDD of transactions whose `productId` has no matching product
    */
  def transactionsWithMissingProducts(transactions: RDD[Transaction], products: RDD[Product]): RDD[Transaction] = {
    val transactionsByProduct = transactions.map(transaction => transaction.productId -> transaction)
    val productsById = products.map(product => product.productId -> product)

    transactionsByProduct
      .leftOuterJoin(productsById)
      .flatMap {
        case (_, (transaction, None))    => Some(transaction)
        case (_, (_, Some(_)))           => None
      }
  }
}
