package ecommerce.analytics

import ecommerce.model.Transaction

/** Pure analytics functions over [[Transaction]] data.
  *
  * Every function in this object is intended to be a pure function:
  * no side effects, no I/O, no mutable state, and no Spark dependency
  * where possible. This keeps the analytics layer independently testable.
  */
object TransactionAnalytics {

  /** Computes the total revenue generated by a single transaction.
    *
    * @param transaction the transaction to evaluate
    * @return price multiplied by quantity
    */
  def revenue(transaction: Transaction): Double =
    transaction.price * transaction.quantity

  // TODO: def revenueByCategory(transactions: Seq[Transaction]): Map[String, Double]
  // TODO: def purchasesByCountry(transactions: Seq[Transaction]): Map[String, Int]
  // TODO: def topProducts(transactions: Seq[Transaction], topN: Int): Seq[(Long, Double)]
  // TODO: def topCustomers(transactions: Seq[Transaction], topN: Int): Seq[(Long, Double)]
  // TODO: def averageTransactionValue(transactions: Seq[Transaction]): Double
}
