package ecommerce.analytics

import ecommerce.model.Transaction
import org.apache.spark.rdd.RDD

/** Analytics functions over [[Transaction]] data.
  *
  * This object is analytics-only: it does not read files, parse CSV, write
  * files, know file paths, or print to the console. Parsing raw lines into
  * transactions is the responsibility of [[ecommerce.parsing.TransactionParser]]
  * (pure, single-record) and [[ecommerce.parsing.TransactionRDDParser]]
  * (Spark RDD transformation).
  *
  * The single-transaction functions (such as `revenue`) and the predicate
  * `minimumPrice` are pure and require no Spark dependency, so they can be
  * unit tested without starting a SparkSession. The RDD-based functions
  * demonstrate the required functional Spark operations (`map`,
  * `reduceByKey`) while still delegating all business rules to pure helpers.
  */
object TransactionAnalytics {

  /** Computes the total revenue generated by a single transaction.
    *
    * @param transaction the transaction to evaluate
    * @return price multiplied by quantity
    */
  def revenue(transaction: Transaction): Double =
    transaction.price * transaction.quantity

  /** A curried predicate that checks whether a transaction's price meets
    * a given minimum threshold.
    *
    * Currying `minimum` separately from `transaction` lets callers partially
    * apply the function (e.g. `minimumPrice(50.0)`) to obtain a reusable
    * `Transaction => Boolean` predicate — a closure over `minimum` — which
    * can be passed directly to Spark's `filter`.
    *
    * @param minimum     the minimum acceptable price
    * @param transaction the transaction to test
    * @return true if the transaction's price is greater than or equal to `minimum`
    */
  def minimumPrice(minimum: Double)(transaction: Transaction): Boolean =
    transaction.price >= minimum

  /** Computes total revenue per product category.
    *
    * Uses `map` to project each transaction into a `(category, revenue)`
    * pair, then `reduceByKey` to sum revenues per category in a
    * distributed, functional manner (no local collection, no mutable state).
    *
    * @param transactions the RDD of parsed transactions
    * @return an RDD of `(category, totalRevenue)` pairs
    */
  def revenueByCategory(transactions: RDD[Transaction]): RDD[(String, Double)] =
    transactions
      .map(transaction => transaction.category -> revenue(transaction))
      .reduceByKey(_ + _)

  /** Counts the number of transaction records per country.
    *
    * Uses `map` to project each transaction into a `(country, 1)` pair,
    * then `reduceByKey` to sum the counts per country.
    *
    * @param transactions the RDD of parsed transactions
    * @return an RDD of `(country, transactionCount)` pairs
    */
  def purchasesByCountry(transactions: RDD[Transaction]): RDD[(String, Int)] =
    transactions
      .map(transaction => transaction.country -> 1)
      .reduceByKey(_ + _)

  // TODO: def topProducts(transactions: RDD[Transaction], topN: Int): Array[(Long, Double)]
  // TODO: def topCustomers(transactions: RDD[Transaction], topN: Int): Array[(Long, Double)]
  // TODO: def averageTransactionValue(transactions: RDD[Transaction]): Double
}
